### ISSUE TITLE
Implement demo in D3.js

### ISSUE THREAD

**Issue by coderbyheart** [ResourcefulHumans/graph-demo#3]
:moneybag: $100 bounty

We need a third demo with the latest version of the D3.js library.

You can find a network graph demo [here](http://resourcefulhumans.github.io/graph-demo/), which is currently implemented in sigma.js and VivaGraph.js.

The implementation is based on data that is generated dynamically. You use the GraphPopulator, as shown [here](https://github.com/ResourcefulHumans/graph-demo/blob/3bd2400716f1fb3b93ff13e0f897a39a7f0f0759/vivagraph.js#L105).

Result MUST BE submitted as a pull request and follow the structure given in the implementation for sigma.js and VivaGraph.js

So, you will
- add a new file: d3.html
- add a new script: d3.js
- add dependencies to package.json (only npm + make are allowed for the build process)

JS MUST follow standard code-style.

**Comment by martinjuhasz** [comment]
sweet, i could take a look and submit a pr.

**Comment by coderbyheart** [comment]
Yes, go ahead! I reserve this bounty for two weeks for you!

**Comment by coderbyheart** [comment]
Fixed in #4
